Repository krpc/krpc2, pull requests merged in 2023-03, with the labels that each got.

#7 Add ksp2 libs to ci workflow
  .github/workflows/ci.yml
Labels: build-scripts

#8 Add skeleton for Vessel class, remove proof-of-concept properties
  service/spacecenter/src/SpaceCenter.cs
  service/spacecenter/src/Vessel.cs
Labels: service:space-center

#23 Distribute ksp libs using ksp-lib repo
  .github/workflows/ci.yml
Labels: build-scripts

#25 Update ci workflow to work with external pull requests
  .github/workflows/ci.yml
Labels: build-scripts

#27 Release archive packaging
  .github/workflows/ci.yml
  BUILD.bazel
  README.md
Labels: build-scripts

#30 Adds Flight Controls (partially addresses #15)
  .gitignore
  service/spacecenter/src/Control.cs
  service/spacecenter/src/Vessel.cs
  tools/install.sh
Labels: enhancement, service:space-center

#33 Game scenes and pausing
  .gitignore
  server/src/ConfigurationFile.cs
  server/src/KRPC2.cs
  server/src/Utils/GameScenesExtensions.cs
  server/src/Utils/GeometryExtensions.cs
Labels: bug, enhancement, server

#37 Update CI workflow to cache bazel dependencies on Windows
  .github/workflows/ci.yml
Labels: build-scripts

#39 Update to use ksp-lib action from krpc-core
  .github/workflows/ci.yml
Labels: build-scripts
